name: CD

on:
  push:
    branches: [main]

jobs:
  cd:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
        poetry-version:
          - "1.6.1"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry ${{ matrix.poetry-version }}
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ matrix.poetry-version }}
      
      - name: Install dependencies
        run: |
          poetry check --lock
          task install

      - name: Lint
        run: task lint

      - name: Format
        run: task fmt

      - name: Test
        run: task test
      
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly
        run: flyctl deploy --config fly.toml --dockerfile Dockerfile --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
